import os
import sys
from src.exception import CustomException

if __name__=="__main__":
    print("test")